# Generated by Django 3.1.7 on 2021-03-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flicks', '0002_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre_id',
            new_name='genre',
        ),
    ]
