# Generated by Django 3.1.7 on 2021-03-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flicks', '0005_userflick'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflick',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
