# Generated by Django 3.2.6 on 2021-09-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flicks', '0007_auto_20210927_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
    ]
