# Generated by Django 3.2.6 on 2021-09-28 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flicks', '0009_remove_movie_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userflick',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='flicks.movie'),
        ),
    ]
