# Generated by Django 3.2.6 on 2021-09-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flicks', '0010_alter_userflick_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
